language: node_js
node_js: 
  - 6
cache:
  directories:
   - node_modules
   - ./client/node_modules
  language: node_js
env:
   - TEST_DIR=tilt-client
   - TEST_DIR=tilt-server
script: cd $TEST_DIR && npm install && npm testt