language: node_js
node_js: 
  - 6
cache:
  directories:
   - node_modules
   - ./client/node_modules
   language: node_js
   node_js:
     - "0.11"
     - "0.10"
   env:
     - TEST_DIR=tilt-client
   script: cd $TEST_DIR && npm install && npm test